sudo: false

language:
  - python

python:
  - 2.7
  - 3.6

install:
  - pip install -r requirements.txt

script:
  - pycodestyle theOracle
  - pytest --verbose --capture=no theOracle
  - pip install .

notifications:
  email: false